/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.sadko.androblogger;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int html_icon=0x7f020000;
        public static final int ic_add_profile=0x7f020001;
        public static final int ic_delete=0x7f020002;
        public static final int ic_edit=0x7f020003;
        public static final int ic_exit=0x7f020004;
        public static final int ic_preview=0x7f020005;
        public static final int ic_revert=0x7f020006;
        public static final int ic_save=0x7f020007;
        public static final int ic_send=0x7f020008;
        public static final int ic_update=0x7f020009;
        public static final int ic_view=0x7f02000a;
        public static final int icon=0x7f02000b;
        public static final int img_icon=0x7f02000c;
        public static final int logo=0x7f02000d;
    }
    public static final class id {
        public static final int BackToCreateBlogEntry=0x7f050022;
        public static final int BackToMainActivities=0x7f05000b;
        public static final int BackToMainActivity=0x7f050015;
        public static final int BackToViewBlog=0x7f05002c;
        public static final int BackToViewPost=0x7f050025;
        public static final int BlogTitle=0x7f050024;
        public static final int ChoiceProfileAndViewBlog=0x7f05001c;
        public static final int Comments=0x7f05002d;
        public static final int ConfigureLayout=0x7f05000e;
        public static final int Content=0x7f050008;
        public static final int CreateNewPost=0x7f05001d;
        public static final int CreateProfile=0x7f05001a;
        public static final int DeletePost=0x7f050026;
        public static final int Exit=0x7f05001f;
        public static final int FETCH_BUTTON_ID=0x7f050016;
        public static final int LayoutForButtons=0x7f05000a;
        public static final int LayoutForLogo=0x7f050018;
        public static final int LinearLayout01=0x7f050002;
        public static final int LinearLayout02=0x7f05002e;
        public static final int LinearLayout03=0x7f050028;
        public static final int LinearLayout04=0x7f050031;
        public static final int LinearLayout05=0x7f050033;
        public static final int Logo=0x7f050019;
        public static final int MainLayout=0x7f05000d;
        public static final int Password=0x7f050014;
        public static final int PostAuthor=0x7f05002f;
        public static final int PostContent=0x7f05002b;
        public static final int PostID=0x7f050030;
        public static final int PostPublishDate=0x7f050032;
        public static final int PostTitle=0x7f05002a;
        public static final int PostUpdateDate=0x7f050034;
        public static final int Preview=0x7f05000c;
        public static final int PreviewContent=0x7f050021;
        public static final int PreviewTitle=0x7f050020;
        public static final int ProfileName=0x7f050010;
        public static final int Publish=0x7f050023;
        public static final int Save=0x7f050017;
        public static final int TextPassword=0x7f050013;
        public static final int TextPostContent=0x7f050009;
        public static final int TextPostTitle=0x7f050007;
        public static final int TextProfileName=0x7f05000f;
        public static final int TextUsername=0x7f050011;
        public static final int TextView01=0x7f05001b;
        public static final int TextView02=0x7f050029;
        public static final int Title=0x7f050006;
        public static final int TopPanel=0x7f050027;
        public static final int Username=0x7f050012;
        public static final int ViewBlog=0x7f05001e;
        public static final int img=0x7f050001;
        public static final int text1=0x7f050003;
        public static final int text2=0x7f050005;
        public static final int text3=0x7f050004;
        public static final int vw1=0x7f050000;
    }
    public static final class layout {
        public static final int commentrow=0x7f030000;
        public static final int createblogentry=0x7f030001;
        public static final int createprofile=0x7f030002;
        public static final int main=0x7f030003;
        public static final int previewandpublish=0x7f030004;
        public static final int row=0x7f030005;
        public static final int viewblog=0x7f030006;
        public static final int viewcomments=0x7f030007;
        public static final int viewpost=0x7f030008;
    }
    public static final class string {
        public static final int app_name=0x7f040001;
        public static final int hello=0x7f040000;
        public static final int service_blogger_description=0x7f040002;
    }
}
